export const MODULE = "furu-sc"; //module name
export const MODULE_NAME = 'Furukai\'s simple crafting'; //module full name
export const MODULE_DIR = `modules/${MODULE}`; //module folder
export const RECIPES = "recipes";
export const DATA_DEFAULT_FOLDER = `/Crafting_Data`;
export const DEFAULT_RECIPES_DATA = `${DATA_DEFAULT_FOLDER}/${RECIPES}.json`; //recipes json file
export const CRAFT_MENU_TEMPLATE = `${MODULE_DIR}/templates/simple-crafting.hbs`;
export const QUANTITY_CONFIG_TEMPLATE = `${MODULE_DIR}/templates/quantity-config.hbs`;
export const CRAFT_MENU_ID = `${MODULE}-craft-menu`;
export const QUANTITY_CONFIG = `${MODULE}-quantity-config`;